# Generated by Django 3.2 on 2022-05-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('detail', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('imagePath', models.ImageField(blank=True, null=True, upload_to='products')),
            ],
        ),
    ]
