# Generated by Django 3.2 on 2022-06-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_product_imagepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagePath',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
